# app/utils/food_database.py

indian_foods = [
    {"name": "Roti", "calories": 80},
    {"name": "Paneer", "calories": 265},
    {"name": "Dal", "calories": 150},
    {"name": "Rice", "calories": 130},
    {"name": "Chicken Curry", "calories": 240},
    {"name": "Samosa", "calories": 262},
    {"name": "Dosa", "calories": 133},
    {"name": "Idli", "calories": 58},
    {"name": "Chole", "calories": 210},
    {"name": "Bhature", "calories": 300},
    {"name": "Paratha", "calories": 150},
    {"name": "Upma", "calories": 180},
    {"name": "Poha", "calories": 180},
    {"name": "Vada", "calories": 180},
    {"name": "Aloo Sabzi", "calories": 140},
    {"name": "Rajma", "calories": 215},
    {"name": "Pulao", "calories": 200},
    {"name": "Biryani", "calories": 290},
    {"name": "Cutlet", "calories": 150},
    {"name": "Pakora", "calories": 170},
    {"name": "Kofta", "calories": 250},
    {"name": "Palak Paneer", "calories": 240},
    {"name": "Chana Masala", "calories": 210},
    {"name": "Mutter Paneer", "calories": 260},
    {"name": "Aloo Paratha", "calories": 220},
    {"name": "Curd", "calories": 60},
    {"name": "Butter Naan", "calories": 180},
    {"name": "Bread", "calories": 70},
    {"name": "Egg", "calories": 78},
    {"name": "Fish Curry", "calories": 200},
    {"name": "Milk", "calories": 103},
    {"name": "Banana", "calories": 90},
    {"name": "Apple", "calories": 52},
    {"name": "Orange", "calories": 47},
    {"name": "Grapes", "calories": 67},
    {"name": "Mango", "calories": 99},
    {"name": "Pineapple", "calories": 50},
    {"name": "Papaya", "calories": 59},
    {"name": "Lassi", "calories": 160},
    {"name": "Halwa", "calories": 300},
    {"name": "Gulab Jamun", "calories": 175},
    {"name": "Rasgulla", "calories": 125},
    {"name": "Kheer", "calories": 180},
    {"name": "Jalebi", "calories": 150},
    {"name": "Ice Cream", "calories": 200},
    {"name": "Tea", "calories": 30},
    {"name": "Coffee", "calories": 40},
    {"name": "Vegetable Soup", "calories": 80},
    {"name": "Corn", "calories": 100},
    {"name": "Sprouts", "calories": 90},
    {"name": "Green Salad", "calories": 40},
    {"name": "Sandwich", "calories": 180},
    {"name": "Maggi", "calories": 205},
    {"name": "Pav Bhaji", "calories": 350},
    {"name": "Vada Pav", "calories": 295},
    {"name": "Misal Pav", "calories": 350},
    {"name": "Bhel Puri", "calories": 150},
    {"name": "Sev Puri", "calories": 210},
    {"name": "Dhokla", "calories": 160},
    {"name": "Khichdi", "calories": 200},
    {"name": "Thepla", "calories": 90},
    {"name": "Undhiyu", "calories": 280},
    {"name": "Sheera", "calories": 250},
    {"name": "Sabudana Khichdi", "calories": 300},
    {"name": "Thalipeeth", "calories": 150},
    {"name": "Modak", "calories": 120},
    {"name": "Shrikhand", "calories": 220},
    {"name": "Aamras", "calories": 130},
    {"name": "Zunka", "calories": 200},
    {"name": "Bhakri", "calories": 140},
    {"name": "Kanda Poha", "calories": 190},
    {"name": "Besan Chilla", "calories": 140},
    {"name": "Methi Thepla", "calories": 120},
    {"name": "Batata Wada", "calories": 290},
    {"name": "Kachori", "calories": 240},
    {"name": "Sabji", "calories": 130},
    {"name": "Tofu", "calories": 80},
    {"name": "Tofu Curry", "calories": 190},
    {"name": "Oats", "calories": 150},
    {"name": "Oats Upma", "calories": 170},
    {"name": "Veg Frankie", "calories": 220},
    {"name": "Chana Chaat", "calories": 160},
    {"name": "Sprouts Salad", "calories": 100},
    {"name": "Veg Wrap", "calories": 180},
    {"name": "Paneer Roll", "calories": 260},
    {"name": "Moong Dal Chilla", "calories": 140},
    {"name": "Lemon Water", "calories": 10},
    {"name": "Buttermilk", "calories": 40},
    {"name": "Soy Milk", "calories": 90},
    {"name": "Egg Curry", "calories": 220},
    {"name": "Rava Upma", "calories": 180},
    {"name": "Paneer Bhurji", "calories": 230}
]

# Fast lookup dictionary
FOOD_DATA = {item["name"].lower(): item["calories"] for item in indian_foods}
